# Generated by Django 4.2 on 2024-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='question_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='seen_questions',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
